name: mobile_dev_project
description: "A Calendar with LLM integration"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  firebase_ai: ^3.5.0
  firebase_core: ^4.2.1
  flutter_dotenv: ^5.0.0
  flutter:
    sdk: flutter
  flutter_markdown: ^0.7.0
  flutter_riverpod: ^3.0.0
  riverpod_annotation: ^3.0.0
  file_picker: ^10.3.3
  intl: ^0.20.2
  icalendar_parser: 2.1.0
  json_annotation: ^4.9.0
  build_runner: ^2.7.1
  json_serializable: ^6.11.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  riverpod_generator: ^3.0.0
  riverpod_lint: ^3.0.0

flutter:
  assets:
    - .env
    - assets/

  uses-material-design: true

include: package:flutter_lints/flutter.yaml

analyzer:
  plugins:
    - custom_lint
